services:
  - type: web
    name: ai-in-accounting
    env: python
    region: us
    buildCommand: ""
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
